-- Units for rent: price is the monthly rent. Every sale query (the voice agent's catalogue, prices,
-- availability) reads SALE units only.
ALTER TABLE units ADD COLUMN transaction_type varchar(10) NOT NULL DEFAULT 'SALE'
  CHECK (transaction_type IN ('SALE','RENT'));
CREATE INDEX idx_units_import_key ON units(workspace_id, (data->>'importKey')) WHERE data->>'importKey' IS NOT NULL;
CREATE INDEX idx_projects_import_key ON projects(workspace_id, (data->>'importKey')) WHERE data->>'importKey' IS NOT NULL;

-- Which File management files have been turned into projects and inventory, and with what result.
CREATE TABLE knowledge_imports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id bigint NOT NULL REFERENCES workspaces(id),
  source_id uuid NOT NULL,
  version integer,
  file_name varchar(255),
  status varchar(20) NOT NULL CHECK (status IN ('PENDING','IMPORTED','EMPTY','FAILED','REMOVED')),
  projects integer NOT NULL DEFAULT 0,
  units integer NOT NULL DEFAULT 0,
  skipped integer NOT NULL DEFAULT 0,
  message varchar(1000),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (workspace_id, source_id)
);
