"""Writes the root .env for a local full-stack run from your provider keys.

    python3 scripts/local_env.py [--keys .env.local-secrets] [--public-url https://xxxx.ngrok-free.app]

Provider keys (Sarvam, Deepgram, VoiceLink, OpenAI) are read from --keys. Internal secrets
(database password, JWT, service account, inter-service tokens) are generated once and kept on
re-runs. Both files are git-ignored; never commit either.
"""

from __future__ import annotations

import argparse
import secrets
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FROM_KEYS = ["SARVAM_API_KEY", "DEEPGRAM_API_KEY", "LLM_FALLBACK_MODEL", "GOOGLE_CLOUD_PROJECT",
             "GOOGLE_CLOUD_LOCATION", "VOICE_LINK_BASE_URL", "VOICE_LINK_USERNAME", "VOICE_LINK_PASSWORD",
             "VOICE_LINK_DID_NUMBER", "VOICE_LINK_CLIENT_ID", "VOICE_LINK_WEBHOOK_TOKEN", "BUILDER_NAME",
             "DEFAULT_OUTBOUND_LANGUAGE", "OPENAI_API_KEY", "OPENAI_EXTRACTION_MODEL", "SERVICE_ACCOUNT_EMAIL"]
GENERATED = ["POSTGRES_PASSWORD", "JWT_SECRET", "DEMO_PASSWORD", "SERVICE_ACCOUNT_PASSWORD", "RAG_SERVICE_TOKEN",
             "RAG_VOICE_TOKEN", "VOICE_AGENT_API_KEY"]
# Speech tuning the agent was deployed with (deploy/azure/render_agent.py).
TUNING = {
    "LLM_PRIMARY_MODEL": "sarvam-105b-conversations", "LLM_PRIMARY_REASONING_EFFORT": "none",
    "SARVAM_LLM_RATE_LIMIT_PER_MIN": "120", "SARVAM_STT_API": "streaming", "SARVAM_TTS_SPEAKER": "ishita",
    "TTS_PRIMARY": "sarvam_streaming", "SARVAM_TTS_MODEL": "bulbul:v3", "SARVAM_TTS_PACE": "1.0",
    "SARVAM_STT_MODEL": "saaras:v3-realtime", "SARVAM_STT_STREAMING_MODEL": "saaras:v3",
    "SARVAM_STT_STREAM_TYPE": "fast", "SARVAM_STT_MODE": "codemix", "SARVAM_STT_LANGUAGE_CODE": "auto",
    "SARVAM_STT_STREAMING_LANGUAGE_CODE": "unknown", "SARVAM_STT_HIGH_VAD_SENSITIVITY": "false",
    "BARGE_IN_MIN_SPEECH_MS": "600",
    "STT_FLUSH_AFTER_MS": "150", "TTS_OUTPUT_GAIN": "1.0",
    "VOICE_LINK_CAPTURE_MESSAGES": "20", "DEFAULT_INBOUND_LANGUAGE": "hi", "LANGUAGE_SWITCH_CONFIDENCE": "0.6",
}


def read(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if path.exists():
        for line in path.read_text().splitlines():
            if "=" in line and not line.lstrip().startswith("#"):
                key, _, value = line.partition("=")
                values[key.strip()] = value.strip().strip('"')
    return values


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--keys", default=str(ROOT / ".env.local-secrets"))
    parser.add_argument("--public-url", default="")
    parser.add_argument("--provider-mode", default="live", choices=["live", "fake"])
    args = parser.parse_args()
    keys = read(Path(args.keys))
    existing = read(ROOT / ".env")
    env: dict[str, str] = {}
    for name in GENERATED:
        env[name] = existing.get(name) or (secrets.token_urlsafe(18) if name == "DEMO_PASSWORD"
                                           else secrets.token_hex(24))
    env.update({
        "POSTGRES_HOST": "db", "POSTGRES_PORT": "5432", "POSTGRES_DB": "estra_os", "POSTGRES_USER": "estraos",
        "SPRING_FLYWAY_ENABLED": "true", "SPRING_PROFILES_ACTIVE": "demo", "INTEGRATIONS_MODE": "mock",
        "API_PORT": existing.get("API_PORT", "8080"),
        "VITE_API_URL": f"http://localhost:{existing.get('API_PORT', '8080')}/api/v1", "CORS_ALLOWED_ORIGINS": "http://localhost:3000",
        "SERVICE_ACCOUNT_WORKSPACE_ID": "1", "SERVICE_ACCOUNT_ADMIN_EMAILS": "admin@estraos.demo",
        "RAG_DATABASE_URL": f"postgresql://estraos:{env['POSTGRES_PASSWORD']}@db:5432/estraos_knowledge",
        "RAG_VOICE_WORKSPACE_ID": "1", "RAG_PROVIDER_MODE": "live" if keys.get("OPENAI_API_KEY") else "fake",
        # The bge reranker adds ~1 GB (torch) to the image and is skipped on CPU within the 150 ms budget
        # most of the time; local runs go without it.
        "RERANKER": "none", "RAG_INSTALL_RERANKER": "false", "PARSER_PROVIDER": "openai",
        "VOICE_PROVIDER_MODE": args.provider_mode, "CRM_MODE": "http",
        "RAG_PORT": existing.get("RAG_PORT", "8090"), "VOICE_AGENT_PORT": existing.get("VOICE_AGENT_PORT", "8081"),
    })
    env.update({k: keys[k] for k in FROM_KEYS if keys.get(k)})
    env.setdefault("SERVICE_ACCOUNT_EMAIL", "voice-agent@estraos.internal")
    env.update(TUNING)
    public = (args.public_url or existing.get("PUBLIC_HTTP_BASE_URL", "")).rstrip("/")
    if public:
        env["PUBLIC_HTTP_BASE_URL"] = public
        env["PUBLIC_WS_BASE_URL"] = public.replace("https://", "wss://")
        token = env.get("VOICE_LINK_WEBHOOK_TOKEN", "")
        env["VOICE_LINK_WEBHOOK_URL"] = f"{public}/telephony/voicelink/webhook" + (f"?token={token}" if token else "")
    lines = ["# Generated by scripts/local_env.py — local only, git-ignored. Never commit."]
    lines += [f"{k}={v}" if " " not in v else f'{k}="{v}"' for k, v in env.items()]
    target = ROOT / ".env"
    target.write_text("\n".join(lines) + "\n")
    target.chmod(0o600)
    print(f"wrote {target} ({len(env)} settings); demo login admin@estraos.demo / DEMO_PASSWORD in .env")


if __name__ == "__main__":
    main()
